### PR TITLE
feat: added slider component in documentation

### PR DESCRIPTION
**Pull request by dev-prabhat**

### CODE REVIEW

**Review by zoyatanweer — APPROVED** [review]
- clean code and understandable
- nice use of comments to separate out the components
- good to merge

**Review by iRohitGaur — APPROVED** [review]
Good to merge 👍🏻

**Review by sudipkundu999 — APPROVED** [review]
Good work. Good to merge

**Review by srishtigautam21 — APPROVED** [review]
Good to merge

**Pull request merged**
